### ISSUE TITLE
[Bug] java connect `arana` error.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#449]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
Exception in thread "main" java.sql.SQLException: Unknown system variable 'query_cache_size'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at arana.TestInsert.main(TestInsert.java:17)
```

```
2022-10-09T18:56:23.402+0800    ERROR   mysql/execute_handle.go:107     get dataset error 7: Unknown system variable 'query_cache_size' (errno 1193) (sqlstate HY000)
github.com/arana-db/arana/pkg/mysql.(*Listener).handleQuery
        /Users/dongzonglei/source_code/Github/arana/pkg/mysql/execute_handle.go:107
github.com/arana-db/arana/pkg/mysql.(*Listener).ExecuteCommand
        /Users/dongzonglei/source_code/Github/arana/pkg/mysql/server.go:555
github.com/arana-db/arana/pkg/mysql.(*Listener).handle
        /Users/dongzonglei/source_code/Github/arana/pkg/mysql/server.go:207
2022/10/09 18:56:28 Post "http://localhost:14268/api/traces": dial tcp 127.0.0.1:14268: connect: connection refused
```

**Comment by dongzl** [comment]
ref  #314

**Comment by jjeffcaii** [comment]
Which version of mysql-connector-java?

**Comment by dongzl** [comment]
> Which version of mysql-connector-java?

The same error：

```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.30</version>
        </dependency>
```
```
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.47</version>
        </dependency>
```
